### ISSUE TITLE
PA Review - Spots Search

### ISSUE THREAD

**Issue by c-noonan** [c-noonan/AirBnweee#8]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds to demonstrate the feature
 - [x] Users can look up certain locations and multiple options are displayed

**Comment by c-noonan** [comment]
Let me know any comments you have!

**Comment by anastassia-b** [comment]
Awesome work! At our meeting today we discussed adding the park names to the description of the spots such that you can search per area.
